version: "3.9"

services:

  backend:
    build: .
    container_name: mlops-backend
    ports:
      - "80:80"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mlflow-server
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 80 --reload

  mlflow-server:
    image: python:3.12
    command: >
      bash -c "pip install mlflow && mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root ./mlruns
      --serve-artifacts
      --allowed-hosts '*'"