name: Deploy MLOps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to ACR
        run: |
          echo ${{ secrets.AZURE_REGISTRY_PASSWORD }} | docker login ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }} \
          -u ${{ secrets.AZURE_REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/mlops-backend:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/mlops-backend:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/mlops-backend:latest